Release/2.4.0
ridibooks-docker/ridiselect-apache-base pull request #2
Opened 2020-02-18 07:41 UTC by Devgrapher

Blackfire를 제거하고 Datadog 설치를 추가했습니다.
Datadog설치파일 경로에 버전이 들어있어서 일단 ENV로 추출은 했는데 더 좋은방법이 있을지 고민되네요.

2020-02-18 16:44 UTC, imkitae requested changes

2020-02-18 16:44 UTC, imkitae commented on README.md
> +- DD_TRACE_AGENT_PORT (default: 8126)
그냥 `agent`와 `trace agent`가 서로 다른 개념인가요? Datadog 구조가 어떤지 잘 모르겠지만, 혹시 같은 개념이라면 접두사를 일치시켜야 할 것 같습니다. 저는 DD_AGENT_*가 마음에 들지만, 결정은 브렌님이 해주세요.

2020-02-18 16:44 UTC, imkitae commented on docker-entrypoint.sh
> +    export DD_TRACE_ENABLED=0
`DD_TRACE_ENABLED`와 `DD_ENABLED`를 분리해두신 이유가 궁금합니다. 둘 중 하나만 사용하면 될 것 같아서요.

2020-02-19 00:30 UTC, Devgrapher commented on README.md
> +- DD_TRACE_AGENT_PORT (default: 8126)
둘다 같은 개념이라고 봐도 무방할것 같습니다. 두 이름은 Datadog에서 제공하는 환경변수이름이라 굳이 바꿀필요는 없을것 같아요.

2020-02-19 00:33 UTC, Devgrapher commented on docker-entrypoint.sh
> +    export DD_TRACE_ENABLED=0
`DD_TRACE_ENABLED`는 Datadog에서 요구하는 환경변수값입니다. 그런데 이 값이 기본값이 1이거든요. 기본값을 0으로 두고싶었어요. 그래서 `DD_ENABLED`라는 값을 추가해서 `DD_TRACE_ENABLED`를 제어한거고요. `DD_TRACE_ENABLED`는 결과적으로 사용자가 사용할 필요 없고 `DD_ENABLED`만 쓰기를 의도한건데, 더 좋은 방법이 있을까요?

2020-02-19 03:01 UTC, imkitae commented on docker-entrypoint.sh
> +    export DD_TRACE_ENABLED=0
사용자가 DD_TRACK_ENABLED를 정의한 경우는 내버려두고, 정의하지 않았을 때만 entrypoint에서 0으로 정의하면 될 것 같습니다.

2020-02-19 03:02 UTC, imkitae commented
LGTM 🙂

2020-02-19 03:03 UTC, imkitae approved these changes

2020-02-19 05:58 UTC, merged